apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-worker
spec:
  selector:
    matchLabels:
      app: vote-worker
  template:
    metadata:
      labels:
        app: vote-worker
    spec:
      containers:
      - name: vote-worker
        image: ${VOTE_WORKER}:latest
        env:
        - name: FROM_REDIS_HOST
          value: "1"
        - name: TO_REDIS_HOST
          value: "1"
        resources:
          limits:
            memory: "256Mi"
            cpu: "200m"
        ports:
        - containerPort: 8080
